// This file contains the initial product data for the store.
// In a real app, this would come from a backend or database.

export interface StoreProduct {
  id: string;
  name: string;
  category: string;
  price: number;
  previousPrice?: number;
  description?: string;
  image?: string;
  tags?: string[];
  rating?: number;
  isNew?: boolean;
  onSale?: boolean;
  nutrition?: {
    calories?: number;
    protein?: number;
    carbs?: number;
    fat?: number;
    allergens?: string[];
  };
}

export const products: StoreProduct[] = [
  {
    id: 'p001',
    name: 'Whey Protein Isolate',
    category: 'Supplements',
    price: 3199,
    previousPrice: 3799,
    description: 'Fast-absorbing whey isolate for muscle recovery and lean mass support.',
    image: 'https://source.unsplash.com/900x700/?whey,protein',
    tags: ['protein', 'muscle', 'supplement', 'recovery', 'strength'],
    rating: 4.8,
    onSale: true,
    nutrition: { protein: 26, allergens: ['milk'] },
  },
  {
    id: 'p002',
    name: 'ProGrip Yoga Mat',
    category: 'Gear',
    price: 1299,
    previousPrice: 1699,
    description: 'Cushioned anti-slip mat made for yoga, mobility, and home training.',
    image: 'https://source.unsplash.com/900x700/?yoga,mat',
    tags: ['yoga', 'gear', 'mobility'],
    rating: 4.6,
    onSale: true,
  },
  {
    id: 'p003',
    name: 'Natural Almond Butter',
    category: 'Food & Drink',
    price: 549,
    description: 'Creamy almond butter with zero added sugar and no palm oil.',
    image: 'https://source.unsplash.com/900x700/?almond,butter',
    tags: ['almond', 'healthy', 'food', 'energy'],
    rating: 4.7,
    nutrition: { protein: 7, fat: 16, allergens: ['nuts'] },
  },
  {
    id: 'p004',
    name: 'Electrolyte Hydration Drink',
    category: 'Food & Drink',
    price: 249,
    previousPrice: 299,
    description: 'Low-sugar hydration blend with essential electrolytes.',
    image: 'https://source.unsplash.com/900x700/?sports,drink,bottle',
    tags: ['hydration', 'drink', 'electrolytes', 'recovery'],
    rating: 4.4,
    onSale: true,
    nutrition: { calories: 40, carbs: 9 },
  },
  {
    id: 'p005',
    name: 'Adjustable Dumbbell Set',
    category: 'Gear',
    price: 6999,
    previousPrice: 8499,
    description: 'Space-saving adjustable dumbbells for strength workouts.',
    image: 'https://source.unsplash.com/900x700/?dumbbell,gym',
    tags: ['gear', 'strength', 'home-gym', 'muscle'],
    rating: 4.9,
    onSale: true,
  },
  {
    id: 'p006',
    name: 'Stainless Steel Shaker',
    category: 'Accessories',
    price: 799,
    description: 'Leak-proof 700ml shaker bottle with mixing ball.',
    image: 'https://source.unsplash.com/900x700/?shaker,bottle',
    tags: ['accessory', 'shaker', 'protein'],
    rating: 4.5,
    isNew: true,
  },
  {
    id: 'p007',
    name: 'Omega-3 Fish Oil',
    category: 'Health',
    price: 999,
    description: 'Daily omega-3 support for heart and joint health.',
    image: 'https://source.unsplash.com/900x700/?fish,oil,supplement',
    tags: ['health', 'heart', 'recovery', 'supplement'],
    rating: 4.6,
    isNew: true,
  },
  {
    id: 'p008',
    name: 'Aloe Cooling Body Lotion',
    category: 'Body Care',
    price: 449,
    description: 'Hydrating body lotion with aloe and vitamin E.',
    image: 'https://source.unsplash.com/900x700/?body,lotion,skincare',
    tags: ['body-care', 'skin', 'recovery'],
    rating: 4.3,
  },
  {
    id: 'p009',
    name: 'Plant Protein Bar Pack',
    category: 'Food & Drink',
    price: 899,
    previousPrice: 1099,
    description: '12 high-protein snack bars for pre and post workout fuel.',
    image: 'https://source.unsplash.com/900x700/?protein,bar,snack',
    tags: ['protein', 'snack', 'food', 'energy'],
    rating: 4.5,
    onSale: true,
  },
  {
    id: 'p010',
    name: 'Resistance Band Kit',
    category: 'Gear',
    price: 1599,
    description: '5-band resistance kit for full-body training anywhere.',
    image: 'https://source.unsplash.com/900x700/?resistance,band,fitness',
    tags: ['gear', 'mobility', 'strength', 'home-gym'],
    rating: 4.7,
    isNew: true,
  },
  {
    id: 'p011',
    name: 'Creatine Monohydrate',
    category: 'Supplements',
    price: 1899,
    previousPrice: 2299,
    description: 'Micronized creatine to support power and high-intensity performance.',
    image: 'https://source.unsplash.com/900x700/?creatine,supplement',
    tags: ['supplement', 'strength', 'muscle', 'power'],
    rating: 4.8,
    onSale: true,
  },
  {
    id: 'p012',
    name: 'BCAA Recovery Formula',
    category: 'Supplements',
    price: 1499,
    description: 'Essential amino acids blend for quicker post-workout recovery.',
    image: 'https://source.unsplash.com/900x700/?bcaa,fitness,supplement',
    tags: ['supplement', 'recovery', 'muscle'],
    rating: 4.4,
  },
  {
    id: 'p013',
    name: 'Vitamin D3 + K2',
    category: 'Health',
    price: 899,
    description: 'Daily immune and bone support formula.',
    image: 'https://source.unsplash.com/900x700/?vitamin,capsule',
    tags: ['health', 'immunity', 'supplement'],
    rating: 4.6,
    isNew: true,
  },
  {
    id: 'p014',
    name: 'Joint Support Collagen',
    category: 'Health',
    price: 1299,
    previousPrice: 1599,
    description: 'Collagen peptides blend for joints, skin, and connective tissue.',
    image: 'https://source.unsplash.com/900x700/?collagen,powder',
    tags: ['health', 'recovery', 'joints'],
    rating: 4.5,
    onSale: true,
  },
  {
    id: 'p015',
    name: 'Steel Jump Rope',
    category: 'Gear',
    price: 749,
    description: 'Adjustable speed rope for cardio and conditioning.',
    image: 'https://source.unsplash.com/900x700/?jump,rope,fitness',
    tags: ['gear', 'cardio', 'conditioning'],
    rating: 4.5,
  },
  {
    id: 'p016',
    name: 'Foam Roller Pro',
    category: 'Accessories',
    price: 999,
    description: 'High-density foam roller for muscle release and mobility.',
    image: 'https://source.unsplash.com/900x700/?foam,roller',
    tags: ['accessory', 'recovery', 'mobility'],
    rating: 4.4,
  },
  {
    id: 'p017',
    name: 'Compression Wrist Wraps',
    category: 'Accessories',
    price: 649,
    description: 'Sturdy wrist support for push and press movements.',
    image: 'https://source.unsplash.com/900x700/?wrist,wrap,gym',
    tags: ['accessory', 'strength', 'support'],
    rating: 4.3,
  },
  {
    id: 'p018',
    name: 'Organic Peanut Butter',
    category: 'Food & Drink',
    price: 499,
    description: 'High-protein peanut spread made from roasted peanuts only.',
    image: 'https://source.unsplash.com/900x700/?peanut,butter',
    tags: ['food', 'protein', 'healthy', 'energy'],
    rating: 4.6,
  },
  {
    id: 'p019',
    name: 'Instant Oats Mix',
    category: 'Food & Drink',
    price: 699,
    previousPrice: 799,
    description: 'High-fiber oats blend for quick, healthy breakfast bowls.',
    image: 'https://source.unsplash.com/900x700/?oats,breakfast',
    tags: ['food', 'fiber', 'energy'],
    rating: 4.5,
    onSale: true,
  },
  {
    id: 'p020',
    name: 'HydraSteel Water Bottle',
    category: 'Accessories',
    price: 1099,
    description: 'Insulated stainless bottle keeps drinks cold for 24 hours.',
    image: 'https://source.unsplash.com/900x700/?water,bottle,steel',
    tags: ['accessory', 'hydration', 'gym'],
    rating: 4.7,
    isNew: true,
  },
  {
    id: 'p021',
    name: 'Body Wash Active Fresh',
    category: 'Body Care',
    price: 399,
    description: 'Refreshing post-workout body wash with menthol and aloe.',
    image: 'https://source.unsplash.com/900x700/?body,wash',
    tags: ['body-care', 'hygiene', 'fresh'],
    rating: 4.2,
  },
  {
    id: 'p022',
    name: 'Recovery Bath Salt',
    category: 'Body Care',
    price: 599,
    description: 'Magnesium-rich bath salts to relax sore muscles.',
    image: 'https://source.unsplash.com/900x700/?bath,salt,spa',
    tags: ['body-care', 'recovery', 'relax'],
    rating: 4.4,
    isNew: true,
  },
  {
    id: 'p023',
    name: 'Kettlebell 12kg',
    category: 'Gear',
    price: 3499,
    previousPrice: 3999,
    description: 'Cast-iron kettlebell for swings, squats, and core training.',
    image: 'https://source.unsplash.com/900x700/?kettlebell',
    tags: ['gear', 'strength', 'conditioning'],
    rating: 4.8,
    onSale: true,
  },
  {
    id: 'p024',
    name: 'Energy Gel Pack',
    category: 'Food & Drink',
    price: 799,
    description: 'Quick carb fuel for long workout sessions and endurance runs.',
    image: 'https://source.unsplash.com/900x700/?energy,gel,sports',
    tags: ['food', 'carbs', 'endurance', 'energy'],
    rating: 4.3,
  },
  {
    id: 'p025',
    name: 'Multivitamin Performance',
    category: 'Health',
    price: 1199,
    description: 'Comprehensive daily vitamins for active lifestyles.',
    image: 'https://source.unsplash.com/900x700/?multivitamin,health',
    tags: ['health', 'immunity', 'performance'],
    rating: 4.6,
  },
  {
    id: 'p026',
    name: 'Lifting Gloves',
    category: 'Accessories',
    price: 899,
    description: 'Breathable gym gloves with enhanced grip and palm padding.',
    image: 'https://source.unsplash.com/900x700/?gym,gloves',
    tags: ['accessory', 'strength', 'gear'],
    rating: 4.4,
  },
  {
    id: 'p027',
    name: 'Protein Pancake Mix',
    category: 'Food & Drink',
    price: 1099,
    previousPrice: 1299,
    description: 'High-protein breakfast pancake mix, low sugar and tasty.',
    image: 'https://source.unsplash.com/900x700/?pancake,mix,protein',
    tags: ['food', 'protein', 'breakfast'],
    rating: 4.5,
    onSale: true,
  },
  {
    id: 'p028',
    name: 'Pre-Workout Ignite',
    category: 'Supplements',
    price: 2099,
    description: 'Caffeine-based pre-workout for focus and workout intensity.',
    image: 'https://source.unsplash.com/900x700/?preworkout,supplement',
    tags: ['supplement', 'energy', 'focus', 'performance'],
    rating: 4.7,
    isNew: true,
  },
];
